@startuml
'https://plantuml.com/class-diagram

skinparam linetype polyline
hide empty members


package "Show Proposal" #9bc8ff{
    object ShowProposal <<Entity>> <<Root>>{
        -Description :String
        -AcceptanceEmailContent :String
        -AcceptanceDate :String
        -DroneInventory :Map<DroneModel, NumberOfDrones>
    }

    object ProposalStatus <<Value Object>> {
        -Status: Enum
    }

    object ProposalVideoLink <<Value Object>> {
        -Link :String
    }

    object ProposalCreationDate <<Value Object>>{
        -Date :Date
    }

    object ProposedShowDate<<Value Object>>{
        -Date :Date
    }

    object ProposedDuration<<Value Object>>{
        -Duration :int
    }

    object ProposedNDrones<<Value Object>>{
        -Number :int
    }
    object ProposedPlace<<Value Object>>{
        -longitude: float
        -latitude: float
    }

    object ProposalFigures <<Value Object>>{
    }

   object Insurance <<Value Object>> {
       -Insurance :Int
   }

   object TypeSettings <<Value Object>> {
        -TypeName
   }

  object SimulationReport<<Entity>>{
       -Result :String
       -Description :String
       -Date :Date
   }

   object Instructions <<Value Object>> {
        -PathToCode :String
   }

   object ProposalDronesModel <<Value Object>> {

   }
}

package "Drone Model" #ffa3a3{
object DroneModel <<Root>> <<Entity>>{

}
}
package "Drone " #ffb5a3 {
object Drone <<Entity>> <<Root>>{

}
}



ShowProposal "1"-down->"1..*" ProposalFigures : has
ShowProposal "1" -up-> "1" ProposalStatus :has
ShowProposal "1" -up-> "1..*" ProposalDronesModel :has
ShowProposal"1" -up-> "1" ProposalCreationDate :has
ShowProposal"1" -up-> "1" ProposedDuration :has
ShowProposal"1" -up-> "1" ProposedPlace :has
ShowProposal"1" -up-> "1" ProposedShowDate :has
ShowProposal "1" -up-> "1" ProposedNDrones :has
ShowProposal "1" -up-> "1" Insurance :has
ShowProposal "1"-left->"0..*" SimulationReport
SimulationReport "1" -left-> "1" ProposalVideoLink :has
TypeSettings "1" <-up- "1" ProposalFigures :has
TypeSettings"1" <-left- "1" Instructions :has
TypeSettings "1"-down->"1..*" ProposalDronesModel : has

ProposalDronesModel "1" -down-> "1" DroneModel : contains
DroneModel "1" -right->"1..*" Drone : contains

@enduml