@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

package "Figure " #88ee88{
object Figure <<Entity>> <<Root>>{
    -author:SystemUser
    -creationDate:LocalDate
    -isActive:boolean
}
}

package "Drone Model" #ffa3a3{
object DroneModel <<Root>> <<Entity>>{
 -Name :String
}
}

package "Show Proposal" #9bc8ff{
    object ShowProposal <<Entity>> <<Root>>{
        -Description :String
        -creationDate :LocalDateTime
    }

    object ProposalStatus <<Value Object>> {
        -Status: Enum
    }

    object ProposedNDrones<<Value Object>>{
        -Number :int
    }

    object ProposalFigures <<Value Object>>{
    }

   object DroneTypeSettings <<Value Object>> {

   }

   object DroneInstructions <<Value Object>> {
        -PathToCode :String
   }

   object ProposalDronesModel <<Value Object>> {

   }
}


' --------------------- WITHIN AGGREGATE RELATIONS -------------------------------

ShowProposal "1" --> "1" ProposalStatus :has
ShowProposal "1" --> "1..*" ProposalDronesModel :has
ShowProposal "1"-->"1..*" ProposalFigures : has
DroneTypeSettings "1..*" <-up- "1" ProposalFigures :has
DroneTypeSettings"1..*" -left-> "1" DroneInstructions :has
DroneTypeSettings "1"-->"1" ProposalDronesModel : has
ProposalDronesModel "1" -left-> "1" ProposedNDrones :has


'--------------------- AGGREGATES RELATIONS -----------------------
ProposalFigures "0..*"-up->"1" Figure : contains
ProposalDronesModel "0..*" -right-> "1" DroneModel : contains
@enduml