@startuml
'https://plantuml.com/class-diagram

skinparam linetype polyline



package "Maintenance Type" #234fff{
object MaintenanceType<<Entity>> <<Root>>{
}
object MaintenanceTypeName <<Value Object>>{
-Name :String
}




MaintenanceType "1" -down-> "1" MaintenanceTypeName:has
@enduml