@startuml
'https://plantuml.com/class-diagram

skinparam linetype polyline



package "Figure Category" #ddaddd{
object FigureCategory <<Entity>> <<Root>>{
    -Description :String
}

object FigureCategoryName <<Value Object>>{
    -Name :String
}

object FigureCategoryStatus <<Value Object>>{
    -Status :String
}

object FigureCategoryCreationDate <<Value Object>>{
    -Date :Date
}
}


FigureCategory "1" -up-> "1" FigureCategoryName :has
FigureCategory "1" -left-> "1" FigureCategoryStatus :has
FigureCategory "1" -right-> "1" FigureCategoryCreationDate :has
@enduml