@startuml

title <size:20>Sequence Diagram US318</size>





skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor CRMManager as Actor
participant ":CreateProposalDocumentTemplateUI" as UI <<presentation>>
participant ":CreateProposalDocumentTemplateController" as Controller <<application>>
participant ":ProposalDocumentTemplateBuilder" as Builder <<builder>>
participant ":ProposalDocumentTemplate" as Domain <<domain>>
participant PersistenceContext <<framework>>
participant RepositoryFactory <<framework>>
participant ProposalDocumentTemplateRepository <<repository>>


activate Actor
Actor -> UI: asks to create proposal document template
activate UI
UI -> Controller**: create
activate Controller
UI --> Actor: requests the name and file path of the template file

Actor -> UI: Types name of the show proposal template, and the file path \nof the template file

    UI -> Controller: createShowProposalDocumentTemplate(name, filePath)
        note right of Builder: ShowProposalDocumentTemplateBuilder is used to create \na valid ShowProposalTemplate entity
        Controller -> Builder : create
        activate Builder
        Builder -> Builder : withName(name)
        Builder -> Builder : withFilePath(filePath)
        Builder -> Builder : build()
        Builder -> Domain : build(name, filePath)
        activate Domain
        Domain --> Builder : proposalDocumentTemplate
        deactivate Domain
        Builder --> Controller : proposalDocumentTemplate
deactivate Builder

        Controller -> PersistenceContext : repositories()
        activate PersistenceContext
        PersistenceContext -> RepositoryFactory : create()
        activate RepositoryFactory
        RepositoryFactory -> ProposalDocumentTemplateRepository : create()
        activate ProposalDocumentTemplateRepository
        Controller -> ProposalDocumentTemplateRepository : save(proposalDocumentTemplate)
        ProposalDocumentTemplateRepository --> Controller : proposalDocumentTemplate



    Controller --> UI : proposalDocumentTemplate
    deactivate Controller

    UI-->Actor: Sucess message

deactivate PersistenceContext
deactivate RepositoryFactory
deactivate ProposalDocumentTemplateRepository
deactivate Domain
deactivate Controller
deactivate UI
deactivate Actor
deactivate Builder




@enduml